# API server listen address
# Defauls to: ":8080" which will listen on all avalable interfaces.
# Overwrite with environment variable: REPORTING_LISTEN

# listen: :8080

# List of elasticsearch addresses
# Defauls to: "elasticsearch:9200"
# Overwrite with environment variable: REPORTING_ELASTICSEARCH_ADDRESSES

# elasticsearch_addresses: "http://localhost:9200"

# Devices: index name
# Defauls to: "devices"
# Overwrite with environment variable: REPORTING_ELASTICSEARCH_DEVICES_INDEX_NAME

# elasticsearch_devices_index_name: "devices"

# Devices: number of shards
# Defauls to: 1
# Overwrite with environment variable: REPORTING_ELASTICSEARCH_DEVICES_INDEX_SHARDS

# elasticsearch_devices_index_shards: 1

# Devices: number of replicas
# Defauls to: 0
# Overwrite with environment variable: REPORTING_ELASTICSEARCH_DEVICES_INDEX_REPLICAS

# elasticsearch_devices_index_replicas: 0

# NATS uri
# Defauls to: "nats://localhost:4222"
# Overwrite with environment variable: REPORTING_NATS_URI

nats_uri: "nats://mender-nats:4222"

# NATS stream name
# Defauls to: "WORKFLOWS"
# Overwrite with environment variable: REPORTING_NATS_STREAM_NAME

# nats_stream_name: "WORKFLOWS"

# NATS subscriber topic name
# Defauls to: "default"
# Overwrite with environment variable: REPORTING_NATS_SUBSCRIBER_TOPIC

# nats_subscriber_topic: "reporting"

# NATS subscriber durable name
# Defauls to: "reporting"
# Overwrite with environment variable: REPORTING_NATS_SUBSCRIBER_DURABLE

# nats_subscriber_durable: "reporting"

# Reindex batch size, in number of buffered requests
# Defauls to: 100
# Overwrite with environment variable: REPORTING_REINDEX_BATCH_SIZE

# reindex_batch_size: 100

# Reindex max time, after which reindexing is triggered.
# Defauls to: 1000
# Overwrite with environment variable: REPORTING_REINDEX_MAX_TIME_MSEC

# reindex_max_time_msec: 1000

# Address of the device auth service
# Defaults to: http://mender-device-auth:8080/
# Overwrite with environment variable: REPORTING_DEVICEEAUTH_ADDR

# deviceauth_addr: "http://mender-device-auth:8080/"

# Address of the inventory service
# Defaults to: http://mender-inventory:8080/
# Overwrite with environment variable: REPORTING_INVENTORY_ADDR

# deviceauth_addr: "http://mender-inventory:8080/"
