openapi: 3.0.3

info:
  title: Reporting
  description: |
    Internal API for the reporting service.
  version: "1"

  contact:
    name: Mender Support
    email: support@mender.io
    url: https://mender.io/contact-us

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://mender-reporting:8080/api/internal/v1/reporting

tags:
  - name: Internal API

paths:
  /alive:
    get:
      tags:
        - Internal API
      summary: Get service liveliness status.
      operationId: Check Liveliness
      responses:
        204:
          description: Service is up and serving requests.
        500:
          $ref: '#/components/responses/InternalServerError'

  /inventory/tenants/{tenant_id}/search:
    post:
      tags:
        - Internal API
      summary: Search device inventory data.
      operationId: Device Search
      parameters:
        - in: path
          name: tenant_id
          required: true
          description: Tenant ID to restrct the search context.
          schema:
            type: string
            example: "123456789012345678901234"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchTerms'
            example:
              page: 1
              per_page: 20
              filters:
                - attribute: "SN"
                  scope: "inventory"
                  type: "$eq"
                  value: "1234567890"
              sort:
                - attribute: "system-version"
                  scope: "inventory"
                  order: "asc"
              attributes:
                - attribute: "SN"
                  scope: "inventory"
              device_ids:
                - "571223e6-26d8-4aae-9074-0d12ce710596"
                - "79b29122-7b69-4548-8b72-73139f44eaba"
                - "ed15eec1-5add-495d-9a3c-119dafe85e4c"
                - "b8783fed-103f-4416-b935-3dd1180640c6"
                - "8e5372bc-b28c-4df4-8de2-9fea92e62db3"
      responses:
        200:
          description: OK. Returns a paginated list of devices.
          headers:
            X-Total-Count:
              schema:
                type: integer
                example: 12300
              description: >-
                The total number of matches.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceInventory'
              example:
                - id: "571223e6-26d8-4aae-9074-0d12ce710596"
                  attributes:
                    - name: "SN"
                      value: "1234567890"
                      scope: "inventory"
                  updated_ts: "2021-08-19T10:25:32Z"
                - id: "79b29122-7b69-4548-8b72-73139f44eaba"
                  attributes:
                    - name: "SN"
                      value: "0987654321"
                      scope: "inventory"
                  updated_ts: "2021-08-19T08:03:32Z"
        400:
          $ref: '#/components/responses/InvalidRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'

  /tenants/{tenant_id}/devices/{device_id}/reindex:
    post:
      tags:
        - Internal API
      summary: Start reindexing device attributes.
      operationId: Start Re-indexing
      parameters:
        - in: query
          name: service
          schema:
            type: string
            example: "inventory"
          description: The name of the calling service. # FIXME Guessing here...
        - in: path
          name: device_id
          required: true
          description: ID of the device that needs reindexing.
          schema:
            type: string
            example: "4396a839-8147-4d01-ac7d-fd3edf8f7ad0"
        - in: path
          name: tenant_id
          required: true
          description: ID of tenant owning the device.
          schema:
            type: string
            example: "123456789012345678901234"
      responses:
        201:
          description: Accepted. Re-indexing started.
        400:
          $ref: '#/components/responses/InvalidRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description: >-
            Request ID passed with the request X-MEN-RequestID header
            or generated by the server.
      description: Error descriptor.
      example:
        error: "<error description>"
        request_id: "eed14d55-d996-42cd-8248-e806663810a8"

    Attribute:
      type: object
      properties:
        name:
          type: string
          description: Name of the attribute.
        value:
          description: Value of the attribute.
        scope:
          type: string
          description: The scope the attribute belongs to.
        description:
          type: string
          description: Optional attributes description.
      required:
        - name
        - value

    DeviceInventory:
      type: object
      properties:
        id:
          type: string
          description: Device ID.
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        updated_ts:
          type: string
          format: date-time
          description: >-
            Timestamp of the last update to the device attributes.

    FilterTerm:
      type: object
      properties:
        attribute:
          type: string
          description: Attribute key to compare.
        value:
          description: Filter matching expression.
        type:
          type: string
          enum:
            - "$eq"
            - "$gt"
            - "$gte"
            - "$in"
            - "$lt"
            - "$lte"
            - "$ne"
            - "$nin"
            - "$exists"
            - "$regex"
          description: Type of filtering operation.
        scope:
          type: string
          description: The scope the attribute exists in.
      required:
        - attribute
        - type
        - value

    SortTerm:
      type: object
      properties:
        attribute:
          type: string
          description: Attribute key to sort by.
        scope:
          type: string
          description: Scope the attribute key belongs to.
        order:
          type: string
          enum:
            - asc
            - desc
          description: "Sort order: ascending/descending."
      required:
        - attribute
        - order

    AttributeProjection:
      type: object
      properties:
        attribute:
          type: string
          description: Attribute key to sort by.
        scope:
          type: string
          description: Scope the attribute key belongs to.
      required:
        - attribute

    SearchTerms:
      type: object
      properties:
        page:
          type: integer
          description: Pagination parameter for iterating search results.
        per_page:
          type: integer
          description: Number of devices returned per page.
        filters:
          type: array
          items:
            $ref: '#/components/schemas/FilterTerm'
          description: Filtering terms.
        sort:
          type: array
          items:
            $ref: '#/components/schemas/SortTerm'
          description: Attribute keys to sort by.
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeProjection'
          description: Restrict the attribute result to the selected attributes.
        device_ids:
          type: array
          items:
            type: string
          description: Restrict the result to the given device IDs.

    InternalDevice:
      description: >-
        NOTE: This is an internal flattened representation of DeviceInventory.
        It is currently not exposed by the API.
      type: object
      properties:
        id:
          type: string
        tenantID:
          type: string
        name:
          type: string
        groupName:
          type: string
        status:
          type: string
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

  responses:
    InternalServerError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "internal error"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"

    InvalidRequestError:
      description: Invalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "bad request parameters"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"
